package enum

const (
	ORDER_STATUS_ORDERED        = "ORDERED"
	ORDER_STATUS_IDENTIFIED     = "IDENTIFIED"
	ORDER_STATUS_CANCELLED      = "CANCELLED"
	ORDER_STATUS_PAID           = "PAID"
	ORDER_STATUS_DONE           = "DONE"
	ORDER_STATUS_MACHINE_FAILED = "MACHINE-FAILED"
)
